### ISSUE TITLE
Availability of Documentation/Commented Source Code

### ISSUE THREAD

**Issue by varungohil** [arminbiere/kissat#12]
Hello,

 Is there any sort of documentation available to understand the source code? Or is there a version of source code with comments?

Thank you.

**Comment by arminbiere** [comment]
No, you have to look at CaDiCaL source code which is the pre-decessor, but of course there are some things in Kissat which have not been in CaDiCaL.  However, I have just release a [video](https://youtu.be/II2RhzwYszQ) for the [https://simons.berkeley.edu/talks/sat-solving](url) on SAT solving which also features a new SAT solver [Satch](https://github.com/arminbiere/satchl), which can serve as a gentle introduction into important aspects of such a solver as Kissat.  It is brand new (10 days old) and is still evolving but version 0.2.4 featured in the video is already decent.  I will add more important features soon, but do not plan to make it as low-level optimized as Kissat (at least for a while).
