### ISSUE TITLE
limit check print bug

### ISSUE THREAD

**Issue by asibkamalsada** [arminbiere/kissat#15]
In https://github.com/arminbiere/kissat/blob/8fca2aa223f0766875773cb6e80b2fb2be03503a/src/application.c#L745  there is `application->conflicts` checked twice. My guess is that one of them should instead read `application->decisions`

**Comment by arminbiere** [comment]
Thanks for catching this.  Even though it does not change functionality it might produce unexpected messages.  Will fix in next release.

**Comment by arminbiere** [comment]
Fixed in sc2021 release.
