### ISSUE TITLE
IPASIR compatibility

### ISSUE THREAD

**Issue by srogatch** [arminbiere/kissat#21]
What are your plans for supporting IPASIR interface? It seems to me that there is no way for the following API currently:

1. `void ipasir_assume (void * solver, int lit)`
2. `int ipasir_failed (void * solver, int lit)`
3. `void ipasir_set_learn (void * solver, void * state, int max_length, void (*learn)(void * state, int * clause))`

**Comment by arminbiere** [comment]
Duplicate of #3
