### ISSUE TITLE
What options might influence kissat's behaviour the most?

### ISSUE THREAD

**Issue by jwaldmann** [arminbiere/kissat#25]
(I apologize if this is not the right venue for discussion. Still I hope to get some input - and I will report back my findings as well.)

I noticed (perchance) in some application that setting "xors" to 0 and "walkinitially" to 1 makes kissat faster. 

Rodrigue Konan Tchinda, Clémentin Tayou Djamegni: Pakis (Satcomp 21 proceedings, p 26/27) https://helda.helsinki.fi/handle/10138/333647 configure these options: tier1, chrono, stable, walkinitially, target, phase.

What other candidates are there for options that might have noticeable influence? What kissat version is best for experimentation with these? 

I don't want to go modify kissat's source - just call it (command line or API, example - https://github.com/jwaldmann/ersatz-kissatapi/blob/main/test/twenty-four.hs#L109)

**Comment by arminbiere** [comment]
Yes:  tier1, chrono, stable, walkinitially, target, phase is a good set.  In essence I went over the code and tried to remove
actual code and also options.  What is left in 'sc2022-light' either had some influence on certain benchmarks or is important for testing and (delta-)debugging (such as all those '--...init=' options).  For instance, for hardware miters playing with the '--sweep...' options can give you large benefits (which are problematic for other benchmarks though and not the best you can do for miters anyhow).  So this set is pretty close to a robust setting for SAT competition alike benchmarks.

**Comment by arminbiere** [comment]
I forgot to mention '--shrink'.  This one is very important for huge formulas with many binary clauses (such as those from the planning track in 2020 - where also the CaDiCaL version from Toronto had a big success with shrinking).  It reduces memory usage for sure but has a neutral effect on most other benchmarks (but seems to slightly be harmful for bit-blasting benchmarks).  I would be careful in only changing 'tier1' without also trying/adapting 'tier2'.
