### ISSUE TITLE
How do I make kissat use more CPU resources/time?

### ISSUE THREAD

**Issue by chexo3** [arminbiere/kissat#28]
I want to make/let kissat use more resources to try and find solutions quicker. Is there a way to do this?

**Comment by arminbiere** [comment]
It seems you want to use a parallel solver then?  There are some parallel solver in the competition which use Kissat.  My own parallel solver Gimsatul is independent from Kissat (and slightly slower at least in sequential mode).

**Comment by arminbiere** [comment]
So this became a Gimsatul issue and I am closing it.
