### ISSUE TITLE
Is it possible to get the learned clauses after solving?

### ISSUE THREAD

**Issue by zhaoyu-li** [arminbiere/kissat#30]
Hi,

Is it possible for Kissat to get the learned clauses after solving a SAT instance? In particular, is there a way to output the augmented CNF formula with the learned clauses when the CNF formula is satisfiable?

Thank you!

**Comment by zhaoyu-li** [comment]
Thank you so much! I also notice that CaDiCaL and Kisasat use some techniques (e.g., bounded variable elimination) that make the augmented formula only maintains the satisfiability equivalence rather than logical equivalence. Are there any options besides bounded variable elimination to set to make these solvers maintain the logical equivalence? Thank you!

**Comment by arminbiere** [comment]
Currently both solvers do NOT remove models (by adding clauses which are not implied).  They only use techniques which potentially add models by dropping certain clauses.  If you follow the approach above however, you will not see those dropped clauses (as you ignore the 'd' lines).  So the result is still logically equivalent.  If however you plan the clauses remaining inside the solver, then it is more tricky.  I really recommend then reading our SAT'22 paper, which probably matches what you have in mind, except that we want to store and migrate solver state after short runs (such as 15min Lambda jobs on AWS).

**Comment by zhaoyu-li** [comment]
Thank you so much. I'll read your paper thoroughly.
