### ISSUE TITLE
Run multiple file .cnf.txt then export to a file?

### ISSUE THREAD

**Issue by anhpham197** [arminbiere/kissat#35]
Is there any way to **run multiple files** .cnf.txt (in `build` folder) and **export the result to a file** instead of running each file in turn and then reading the results in the console?
Thanks!

**Comment by arminbiere** [comment]
I am not sure what you are after.  A simple shell script could do that.

**Comment by anhpham197** [comment]
I wanna run multiple file cnf at once time, then I can export the result to a file.

**Comment by arminbiere** [comment]
Yes, this is exactly what simple shell scripting would be able to do. 
I give two options for solving the 'sqrt...' CNFs in 'test/cnf'.

1) If you want to run kissat on all the CNFs separately but concat the output:

```
$ ls test/cnf/sqrt*.cnf|xargs -n 1 kissat
```

You can do this even say for 8 cores in parallel by adding `-P 8` after `-n 1`.

2) If on the other hand you

```
$ (echo 'p cnf 0 0'; sed -e '/^[chp]/d' test/cnf/sqrt*.cnf)|kissat --relaxed
```

**Comment by anhpham197** [comment]
Thanks a ton, @arminbiere . It's exactly what I want. Do you plan to implement **Kissat** on Windows?

**Comment by arminbiere** [comment]
There are ports by others (see also issue #33) and yes I also plan to have ports at one point in the main repro but probably not provide binaries.

**Comment by anhpham197** [comment]
Hope to see your addition soon. Have a nice weekend, @arminbiere

**Comment by DvonHolten** [comment]
well, the reasons against windows exe-files can be understood. 
OTOH, it can be a PITA to setup a c compiler chain just to get some executable. Some people are just interested in _running_ the SAT-solver as a black box. Some projects use makefile, others use cmake.

**Comment by anhpham197** [comment]
Cuz I'm using Sat4j library supporting Windows, then I've tested some problems by Kissat and found that Kissat is extremely good in terms of both solving time and the number of problems solved. Hence, I wanna find another version of Kissat on Windows to test.

**Comment by gsgs2** [comment]
I agree that this would be useful. I.e. for benchmark-sets.

I'm copying all the files into one file,
I wrote a program to read that big file
and extract one instance after the other, 
to file kk
then call 
system(" ./kissat -q kk >> ll");
and postprocess ll
