### ISSUE TITLE
Remove redundant variables

### ISSUE THREAD

**Issue by anhpham197** [arminbiere/kissat#36]
I have a question about the variables in Kissat described following.

```
p cnf 4 2
1 2 0
5 6 0
``` 
**Expected output:** 
``` 
Satisfiable
1 2 5 6 0
```

In `.cnf` file, I have 4 variables `X1, X2, X5, X6` and 2 clauses `X1 v X2 and X5 v X6` as above. For some reason, I don't need to use `X3, X4`, I just use 4 variables `X1, X2, X5, X6` and I expect that the output should return only the value of those variables. However, when I used Kissat to solve this problem,  it showed the following log:

> parse error: maximum variable index exceeded (try '--relaxed' parsing)

Then I edited the number of variables in the header to 6 (`p cnf 6 2`), and I found that Kissat returned the value of both `X3, X4` (it means that it returned full variables from `X1` to the biggest variable - `X6`).

Hence, my **questions** are: 

- [ ] Is it compulsory to use continuous variables in Kissat? 
- [ ] If not, how to get result of only declared variables in `.cnf` file?
- [ ] I tried `--relaxed`, but it only returned the value of `X1, X2, X3, X4` (4 variables as in the header) without the value of `X5, X6`.

**Comment by arminbiere** [comment]
This is just the default behavior of SAT solvers which try to match the expectations of the SAT competition.  If you need something more fancy you need to write an encoder and a backtranslation tool.

**Comment by danielleberre** [comment]
@anhpham197 you do not get the semantic of the p cnf line right.

It is

```
p cnf <maxvarid> <#clauses>
```

maxvarid is the maximum id used for a variable.

it is perfectly legal to use

```
p cnf 10000 2
9999 10000 0
-9999 -10000 0
```

but you will end up, for most SAT solvers, with 10000 values in your solutions 

while

```
p cnf 2 2
1 2 0
-1 -2 0
```

will provide you models with only 2 variables.

**Comment by anhpham197** [comment]
@danielleberre I got it, but in the following case, there will be 10000 values in the range of 1 to 10000 in my solution, my question is that "Does it affect the performance cuz I think that SAT Solver needs more memory to store 10000 values than 2?"
```
p cnf 10000 2 
9999 10000 0
-9999 -10000 0
```

**Comment by danielleberre** [comment]
Exactly. So you should pay attention to number correctly your variables in the CNF file if you want to reduce memory consumption.

**Comment by anhpham197** [comment]
I got it, thanks @danielleberre a lot ^^
