### ISSUE TITLE
Shared library with example usage?

### ISSUE THREAD

**Issue by dgiagio** [arminbiere/kissat#4]
In order to allow Kissat to be used by other languages (Java, .NET, Python, Go, etc.) it would be nice to have it built as a shared library. In addition to that, a simple example on how to use the library would also be great.

**Comment by arminbiere** [comment]
Library usage of Kissat is very limited at this point.  It does not support incremental use.  Regarding shared library building see the answer to issue #2 (you need to add '-fPIC' to configure and link the library yourself for now).

**Comment by andrewvaughanj** [comment]
If you're really after some "real world" API usage examples, see here: https://github.com/CVC4/CVC4/blob/master/src/prop/kissat.cpp

**Comment by arminbiere** [comment]
I found an easy way to build a solver binary with a statically linked solver library and with the same configuration (and 'make') produce a shared library.  This merely needs a '-shared' argument to './configure' to '-fpic', an extra '-shared' linking goal to produce 'libkissat.so' and then just use 'libkissat.a' explicitly when linking 'kissat' and 'missat'.  This will go into the next release.
