### ISSUE TITLE
Remove build.h include

### ISSUE THREAD

**Issue by amatuag** [arminbiere/kissat#41]
This is a minor issue but build.c includes a missing header file "build.h". I think this include can be removed.

#include "build.h"
#include "colors.h"
#include "kissat.h"
#include "print.h"

#include <stdio.h>

const char *kissat_signature (void) { return "kissat-" VERSION; }

**Comment by arminbiere** [comment]
Not really.  This `build.h` is automatically generated by the `generate-build-header.sh` script:

```
$ ./configure
...
$ make
...
../scripts/generate-build-header.sh > build.h
...
gcc -W -Wall -O3 -DNDEBUG -I../build -c ../src/build.c
...
```
Note that `build.o` has a dedicated makefile rule for this purpose.

**Comment by amatuag** [comment]
Oh, sorry about missing that.
