### ISSUE TITLE
Iterative solving for multiple solutions?

### ISSUE THREAD

**Issue by Bikes4Fun** [arminbiere/kissat#55]
Hello, I believe some of the generic libraries (pysat comes to mind) have a method to run the solver iteratively in order to find multiple valid solutions. I wrote a function that performs this task for me, but I was wondering if you may already have something built in?

**Comment by arminbiere** [comment]
Kissat is not incremental at this point as it requires a substantial engineering effort to get this correct in all usage scenarios.   We do have some open issues #3 around that question too.

**Comment by Bikes4Fun** [comment]
Okay thank you! That makes sense. The version I rigged up isn't very robust. If you don't mind giving some personal project advice: Are you familiar with At Most K encoding? If so, do you have any specific advice for this type of encoding with Kissat specifically? I have a large dataset that I know is unsolvable as is, but there are alternatives to the current constraints that I would like to try and find out how to minimize our conflicts.

**Comment by arminbiere** [comment]
For cardinality constraint encoding there are libraries out there, for instance  [pblib](https://github.com/master-keying/pblib) but it is not convenient for the end-user.

**Comment by Bikes4Fun** [comment]
Thank you so much!
