### ISSUE TITLE
kissat_signature not implemented

### ISSUE THREAD

**Issue by deiruch** [arminbiere/kissat#6]
The `kissat_signature` function, as defined here

https://github.com/arminbiere/kissat/blob/baef4609163f542dc08f43aef02ce8da0581a2b5/src/kissat.h#L8

is implemented nowhere.

**Comment by arminbiere** [comment]
Ah yes, I tried to remove all the not yet implemented IPASIR functions but forgot that one.  Since I will start working on full IPASIR support soon, I will fix this during that work.

**Comment by arminbiere** [comment]
Added in sc2021 release.
