### ISSUE TITLE
Descriptions of options --autarky and --autarkeydelay are swapped

### ISSUE THREAD

**Issue by deiruch** [arminbiere/kissat#8]
It appears that the descriptions of the `autarky`- and `autarkeydelay`-options are swapped. From the command-line help:
```
...
  --autarky=<bool>           delay autarky reasoning [true]
  --autarkydelay=<bool>      enable autarky reasoning [true]
...
```

**Comment by arminbiere** [comment]
Thanks, fixed in the internal version.  Will be in the next release.

**Comment by arminbiere** [comment]
Fixed in sc2021 release.
